name: 'check deployment freeze'
description: 'A deployment_freeze_status tag is defined on AWS resource,  '
inputs:
  cluster:
    description: >
      The name of the ecs cluster, inside which the service is defined
    required: true
  github-pat:
    description: >-
      GitHub personal access token
    required: true

runs:
  using: "composite"
  steps:
    - name: init job  
      uses: myriad-actions/init-job@main
      with:
        github-pat: ${{ secrets.github-pat }}
    - name: load testing config
      if: ${{  inputs.environment == 'testing' }} && ${{  env.HOST_MODE == 'ecs' }}
      run: |
        echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-TESTING }}" >> $GITHUB_ENV
    - name: load preprod config
      if: ${{  inputs.environment == 'preprod' }}  && ${{  env.HOST_MODE == 'ecs' }}
      run: |
        echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-PREPROD }}" >> $GITHUB_ENV
    - name: load prod config
      if: ${{  inputs.environment == 'prod' }}  && ${{  env.HOST_MODE == 'ecs' }}
      run: |
        echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-PROD }}" >> $GITHUB_ENV
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS-ROLE-TO-ASSUME }}
        aws-region: ${{ env.AWS-REGION }}
    - name: retrieve ecs value
      if: ${{ env.HOST_MODE == 'ecs' }}
      run: |
        echo DFS=$(aws ecs describe-services --include "TAGS" --services ${{ github.event.repository.name }} --cluster ${{ inputs.cluster }} --query 'services[].tags[?key==`deployment-freeze-status`].value[]' | jq -r ".[]") > $GITHUB_ENV
      shell: bash
    - name: check_freeze_status
      if: ${{ env.DFS != 'unfrozen' }} 
      uses: actions/github-script@main
      with:
        script: core.setFailed('The deployment on ${{ inputs.cluster }}:${{ inputs.service-name }} is frozen.')
