name: 'check deployment freeze'
description: 'A deployment_freeze_status tag is defined on AWS resource,  '
inputs:
  cluster:
    description: >
      The name of the ecs cluster, inside which the service is defined
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS-ROLE-TO-ASSUME }}
        aws-region: ${{ env.AWS-REGION }}
    - name: retrieve tag value
      run: |
        echo DFS=$(aws ecs describe-services --include "TAGS" --services ${{ github.event.repository.name }} --cluster ${{ inputs.cluster }} --query 'services[].tags[?key==`deployment-freeze-status`].value[]' | jq -r ".[]") > $GITHUB_ENV
      shell: bash
    - name: check_freeze_status
      if: ${{ env.DFS != 'unfrozen' }} 
      uses: actions/github-script@main
      with:
        script: core.setFailed('The deployment on ${{ inputs.cluster }}:${{ inputs.service-name }} is frozen.')
