name: 'check deployment freeze'

description: 'A deployment-freeze-status tag is defined on AWS resource,  '

inputs:
  environment:
    description: >-
      one of the testing, preprod or prod envinronment, for the workflow run
    required: true
    type: string
  github-pat:
    description: >-
      GitHub personal access token
    required: true
outputs:
  testing:
    description: >-
      the depolyment frozen status of testing platform
    value: ${{ steps.check-testing-status.outputs.status }}
  preprod:
    description: >-
      the depolyment frozen status of preprod platform
    value: ${{ steps.check-preprod-status.outputs.status }}
  prod:
    description: >-
      the depolyment frozen status of testing platform
    value: ${{ steps.check-prod-status.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: init job  
      uses: myriad-actions/init-job@main
      with:
        github-pat: ${{ inputs.github-pat }}
    - name: load testing config
      if: inputs.environment == 'testing' && env.HOST_MODE == 'ecs'
      run: |
        echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-TESTING }}" >> $GITHUB_ENV
      shell: bash
    - name: load preprod config
      if: inputs.environment == 'preprod' && env.HOST_MODE == 'ecs'
      run: |
        echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-PREPROD }}" >> $GITHUB_ENV
      shell: bash
    - name: load prod config
      if: inputs.environment == 'prod' && env.HOST_MODE == 'ecs'
      run: |
        echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-PROD }}" >> $GITHUB_ENV
      shell: bash
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS-ROLE-TO-ASSUME }}
        aws-region: ${{ env.AWS-REGION }}
    - name: retrieve ecs value
      if: ${{ env.HOST_MODE == 'ecs' }}
      run: |
        echo DFS=$(aws ecs describe-services --include "TAGS" --services ${{ env.ECS_TASK }} --cluster ${{ env.CLUSTER }} --query 'services[].tags[?key==`deployment-freeze-status`].value[]' | jq -r ".[]") > $GITHUB_ENV
      shell: bash
    - name: check_freeze_status
      if: ${{ env.DFS != 'unfrozen' }} 
      uses: actions/github-script@main
      with:
        script: core.setFailed('The deployment on ${{ env.CLUSTER }}:${{ inputs.service-name }} is frozen.')
        
    - name: check-testing-status
      run: |
      [[ ${{ env.HOST_MODE == 'ecs' }} ]] && \ 
      echo "::set-output name=status::$(aws ecs describe-services --include "TAGS" --services ${{ env.ECS_TASK }} --cluster ${{ env.CLUSTER }} --query 'services[].tags[?key==`deployment-freeze-status`].value[]' | jq -r ".[]") || \
      
      
    - name: check-testing-status
